---
- name: Debian | Set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

# NOTE: Despite being called php5, this package works with all versions.
# See https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian
- name: Debian | Install New Relic PHP Agent
  apt:
    pkg: newrelic-php5
  notify:
    - Run New Relic Installer