---
- name: Run New Relic Installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
    - Remove ini
    - Restart PHP-FPM

- name: Restart PHP-FPM
  service: name={{ newrelic_php_fpm_service }} state=restarted
  ignore_errors: yes
  when: newrelic_restart_php_fpm

# NOTE: The newrelic installer creates a default ini file which causes
# a conflict if left in place.
- name: Remove ini
  file:
    path="{{ item }}"
    state="absent"
  with_items:
    - /etc/php/{{ newrelic_php_version }}/cli/conf.d/newrelic.ini
    - /etc/php/{{ newrelic_php_version }}/fpm/conf.d/newrelic.ini
